apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  labels:
    app: docker-registry
type: Opaque
data:
  # how to generate a htpasswd for kubernetes secret
  # this data  will mount at /auth/htpasswd(REGISTRY_AUTH_HTPASSWD_PATH)
  # step 1 :
  #   docker run --entrypoint htpasswd registry:2 -Bbn user password > ./htpasswd
  # step 2 :
  #   cat ./htpasswd | base64 | tr -d '\n'
  # example
  htpasswd: dXNlcjokMnkkMDUkUW9XQU8udXFRMjJ2dC9lRmFCNnhiLmw0WUVtLzRJRzlSZ0ZXMWF6cDFlYTBLUDdNRU81NU8KCg==
  # echo "haSharedSecret" | base64
  haSharedSecret: aGFTaGFyZWRTZWNyZXQK
