kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: docker-registry
  labels:
    app: docker-registry
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 200Gi
  storageClassName: "registry-storage"

